
[site]
title = "Forest Katsch"
url = "https://forestkatsch.com/"

[content]
path = "./content/"

[static]
path = "./static"
output = ""
copy = true

[handlers.strip-summary]
handler = "./handlers/util/strip-summary.ts"

[handlers.markdown]
extensions = [".md"]
handler = "./handlers/markdown.ts"

[handlers.listing]
handler = "./handlers/listing.ts"

[handlers.home]
handler = "./handlers/listing.ts"

[handlers.home.options]
home = true

[handlers.album]
handler = "./handlers/album.ts"

[handlers.image]
extensions = [".jpg", ".png", ".jpeg"]
handler = "./handlers/image.ts"

[handlers.tag]
handler = "./handlers/tag.ts"

[handlers.category]
handler = "./handlers/category.ts"

[transform]
operations = [
  "strip-summary",
  
  "media-metadata-read",
  "media-copy",
  "media-compress",
  "media-thumbnail",

  "album-reference",
  
  "tag-generate",
  "category-generate",

  "content-interpolation",
  
  "@render",
]

[output]
path = "dist"