
title = 'SN9 midway through the flip'
summary = "Two engines should be running, and SN9 shouldn't be quite this close to the ground."
tags = ['starship', 'sn9', 'rocket']

[image.exif.camera]
make = 'Sony'
model = 'ILCE-6400'

+++
