title = "SpaceX ITS Mars Lander Scale"

category = "infographic"

publishDate = 2016-10-30T00:00:00Z

tags = ["infographic-legacy", "vehicle", "scale", "spacex", "spacex-its", "statue-of-liberty"]

#[infographic]
#category = "SpaceX ITS"
#name = "Mars Lander Scale"
#
#aspect = "tall"
#file = "vehicle/spacex-its-lander-scale"
#
#redbubble = "https://www.redbubble.com/people/zlsa/works/24203670-spacex-its-mars-lander-scale"
+++

The [SpaceX ITS](/tags/spacex-its) is huge. This is only the smaller upper stage.

<!--more-->
