title = "SpaceX Falcon 9 Scale"

category = "infographic"

publishDate = 2016-08-03T00:00:00Z

tags = ["infographic-legacy", "vehicle", "scale", "spacex", "spacex-falcon9", "statue-of-liberty"]

#[infographic]
#category = "SpaceX Falcon 9"
#name = "Scale"
#
#aspect = "tall"
#file = "vehicle/spacex-falcon9-scale"
+++

The [SpaceX Falcon 9](/tags/spacex-falcon9) is big. Really big. Mindboggling big.

(But it's peanuts compared to the [SpaceX ITS]({{< ref "infographic/vehicle/spacex-its-lander-scale.md" >}}).)

<!--more-->
