title = "SpaceX Dragon 2 Engine Layout"

category = "infographic"

publishDate = 2016-06-16T00:00:00Z

tags = [
     "infographic-legacy",
     
     "vehicle",
     "components",

     "spacex-superdraco",
     "spacex-draco",

     "spacex",
     "spacex-dragon",
     "spacex-dragon2",
     
     "spacecraft"]

#[infographic]
#category = "SpaceX Dragon 2"
#name = "Engine Layout"
#
#aspect = "wide"
#file = "vehicle/spacex-dragon2-engine-layout"
+++

This is a high-level view of the engines and thrusters in the [SpaceX Dragon 2](/tags/spacex-dragon2).

<!--more-->

<!-- TODO -->
