title = "SpaceX Falcon 9 Transport"

category = "infographic"

publishDate = 2016-08-17T00:00:00Z

tags = [
     "infographic-legacy",
     
     "transport",
     "vehicle",
     
     "spacex",
     "spacex-falcon9-landing-leg",
     "spacex-falcon9",
     "spacex-falcon9-stage-one",
     "spacex-falcon9-stage-two"
]

#[infographic]
#category = "SpaceX Falcon 9"
#name = "Transport"
#
#aspect = "wide"
#file = "vehicle/spacex-falcon9-transport"
+++

The [SpaceX Falcon 9](/tags/spacex-falcon9) is designed to fit on
public roads in the US. Here's how SpaceX transports the different
components.

<!--more-->

<!-- TODO -->
