title = "Illustration for Robert Zubrin's article on Moon Direct for the New Atlantis"

publishDate = 2019-01-14T00:00:00Z

category = "art"

tags = [
     "moon-direct",
     "robert-zubrin",
     "the-new-atlantis",
     
     "moon",
     "moon-crater",
     
     "blender"
     ]

#[art]
#image = "the-new-atlantis-moon-direct"
#
+++

This image was commissioned by [The New Atlantis](https://www.thenewatlantis.com/publications/moon-direct) to accompany an article about Moon Direct by Robert Zubrin, known for his Mars Direct plan.
