
title = 'SN8 aftermath'
summary = "The remains of SN8 (still smoking on the landing pad), and the build site to the right."
tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T17:38:19-06:00

[image.exif.camera]
make = 'Sony'
model = 'ILCE-6400'

+++

On the left: the smoking remains of SN8.

On the right: the build site, and some interested wildlife.