
title = 'SN8 apogee reorientation'
summary = "Starship descends while flipping forwards onto its belly, with residual liquid oxygen venting (or maybe Raptor venting?) still underway."
tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:43:00-06:00
+++

Starship SN8 midway through its reorientation.
Above and to the left is the residual liquid oxygen, vented while SN8 hovered at apogee (probably for a combination of reducing mass and changing mass balance.)

Note the fin deflection: even though it's still more vertical than horizontal, SN8's fore fins are still at nearly full extension while the aft fins are tucked back all the way.

