
title = 'Starship SN8 apogee vent'
summary = "Starship SN8 hovers on a single Raptor engine while dumping liquid oxygen."

tags = ['starship', 'sn8', 'rocket', 'rocket-vent']

publishDate = 2020-12-09T16:42:00-06:00
+++

Starship SN8 hovers on a single Raptor engine while dumping liquid oxygen.

Shortly afterwards, Raptor SN42 gimballed sharply to begin the apogee reorientation, then shut off to allow Starship to flip forward onto its belly.
