
title = 'SN8 passes a bird'
summary = "SN8 flies in the background as a bird casually glides by"
tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:38:57-06:00

[image.exif.camera]
make = 'Sony'
model = 'ILCE-6400'

+++

SN8 ascends thunderously in the background while a bird casually glides by.