
title = 'SN8 engine shutdown #1'
summary = "As SN8 ascends, engines are shut down to reduce acceleration and keep top speed manageable."
tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:39:53-06:00
+++

As SN8 ascends, engines are shut down to reduce acceleration and keep top speed manageable.
This is engine shutdown number 1.