
title = 'SN8 fireball (1)'
summary = "The fireball produced by the impact; this photo was taken about 3 seconds after impact."

tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:44:57-06:00
+++
