
title = 'SN8 fireball (2)'
summary = "The fireball produced by the impact continues to burn itself out; this photo was taken about 7 seconds after impact."

tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:45:01-06:00
+++
