
title = 'SN8 start of landing flip'
summary = "Two Raptor engines relight to flip the spacecraft from horizontal to vertical in preparation for landing."

tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:44:44-06:00

+++
Two Raptor engines relight to flip the spacecraft from horizontal to vertical in preparation for landing.
