
title = 'SN8 landing burn startup'
summary = "A single Raptor engine relights from the header tanks to flip the spacecraft from horizontal to vertical in preparation for landing."

tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:44:43-06:00
+++
