
title = 'SN8 engine-rich combustion'
summary = "Unlike the Falcon 9's Merlin engines, Raptor does not use TEA-TEB ignitor fluid. On Raptor, green is the color of burning copper."

tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:44:52-06:00

+++

During its landing, the single engine powering SN8 through the final seconds of the flight began to burn engine-rich (ingesting large amounts of copper), resulting in an unplanned lithobraking event. The engine-rich combustion was caused by [low pressure in the methane header tank](https://twitter.com/elonmusk/status/1336809767574982658).

It's not very apparent in this edit, but the green flame was incredibly bright (far brighter than normal Raptor breath, and far brighter than the sky.)
