
title = 'SN8 engine ignition'
summary = "Note the interesting lighting effect on the ice-coated tanks."
tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:38:12-06:00

[image.exif.camera]
make = 'Sony'
model = 'ILCE-6400'

+++
