
title = 'SN8 impact'
summary = "The moment of SN8's impact against the landing pad. A lone RCS thruster (or LOX header tank tank vent) is visible at the nose."

tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:44:54-06:00
+++
