
title = 'SN8 launch'
summary = "Taken about 15 seconds after launch, while the vehicle slowly ascends."
tags = ['starship', 'sn8', 'rocket']

publishDate = 2020-12-09T16:38:31-06:00

[license]
name = "CC-BY-SA 4.0"
url = "https://creativecommons.org/licenses/by-sa/4.0/deed.en"

+++

Starship SN8 shortly after liftoff.
Note the orientation of the vehicle, with the fins edge-on towards me.
During the ascent, SN8 rolled back and forth in a controlled manner,
taking the fins from edge-on to face-on and back to nearly edge-on again shortly before apogee.

A crop of this photo is the header image for [Starship on Wikipedia](https://en.wikipedia.org/wiki/SpaceX_Starship)!
(Hence the CC-BY-SA license on this photo.)
<!--(As of [2020-12-28](https://host.zlsadesign.com/SksFA4w6v.png), at least.)-->
