
title = 'SN8 Two birds, one shot'
summary = "A pair of flying machines; one small and lightweight and covered in feathers, one not."
tags = ['starship', 'sn8', 'rocket', 'bellyflop']

publishDate = 2020-12-09T16:44:18-06:00
+++

Starship SN8 slowly descends in the background as a bird flies by in the foreground.
